---
all:
  vars:
    ansible_user: deployer
    ansible_python_interpreter: /usr/bin/python3

  children:
    db_servers:
      hosts:
        stage-db1:
          ansible_host: 10.2.0.5

    app_servers:
      hosts:
        stage-app1:
          ansible_host: 10.2.0.10
