---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3

  children:
    db_servers:
      hosts:
        stage-db1:
          ansible_host: 157.180.74.222

    app_servers:
      hosts:
        stage-app1:
          ansible_host: 77.42.16.6
