---
all:
  vars:
    ansible_user: andrius
    ansible_python_interpreter: /usr/bin/python3

  children:
    db_servers:
      hosts:
        prod-db1:
          ansible_host: 10.1.0.5
          # ansible_host: db1.prod.example.com

    app_servers:
      hosts:
        prod-app1:
          ansible_host: 10.1.0.10
          # ansible_host: app1.prod.example.com
        # prod-app2:
        #   ansible_host: 10.1.0.11
